#!/bin/sh
GLASSFISH_HOME=${GLASSFISH_HOME:-"/opt/glassfish4"}

case "$1" in

start)
        $GLASSFISH_HOME/bin/asadmin start-domain
        ;;
stop)
        $GLASSFISH_HOME/bin/asadmin stop-domain
        ;;
restart)
        $GLASSFISH_HOME/bin/asadmin restart-domain
        ;;
\*)
        echo "Usage: $0 (start|stop|restart|help)"
esac
